### ISSUE TITLE
KeyError: crop

### ISSUE THREAD

**Issue by HenningEMBL** [tischi/fiji-convert-bin-project#2]
Hi Tischi,
I finally got past registration of MIPs and want to do 3D-stack Registration now. The conversion of the mha files into tif using the fiji-convert-bin-project produces an error:
KeyError: crop

Errors:
Started fiji--convert-bin-project.py at Thu Feb 16 16:13:28 CET 2017
Traceback (most recent call last):
  File "D:\TischiReg\fiji-convert-bin-project-master\fiji--convert-bin-project.py", line 454, in <module>
    tbModel = analyze(iDataSet, tbModel, p)
  File "D:\TischiReg\fiji-convert-bin-project-master\fiji--convert-bin-project.py", line 159, in analyze
    if p['crop']:
KeyError: crop

Output:
...
# Files to be analyzed
#
0: E:\EMBL-TEST\Henning\TischiRegSavingTest\3D-Registration--01\16-10-20_LfngT2A3xCh-Dusp4T2A3xVen_E75_4_G2_Average_Subset_E1_ch0_t000.tif--transformed.mha
1: E:\EMBL-TEST\Henning\TischiRegSavingTest\3D-Registration--01\16-10-20_LfngT2A3xCh-Dusp4T2A3xVen_E75_4_G2_Average_Subset_E1_ch0_t001.tif--transformed.mha
2: E:\EMBL-TEST\Henning\TischiRegSavingTest\3D-Registration--01\16-10-20_LfngT2A3xCh-Dusp4T2A3xVen_E75_4_G2_Average_Subset_E1_ch0_t002.tif--transformed.mha
3: E:\EMBL-TEST\Henning\TischiRegSavingTest\3D-Registration--01\16-10-20_LfngT2A3xCh-Dusp4T2A3xVen_E75_4_G2_Average_Subset_E1_ch1_t000.tif--transformed.mha
4: E:\EMBL-TEST\Henning\TischiRegSavingTest\3D-Registration--01\16-10-20_LfngT2A3xCh-Dusp4T2A3xVen_E75_4_G2_Average_Subset_E1_ch1_t001.tif--transformed.mha
5: E:\EMBL-TEST\Henning\TischiRegSavingTest\3D-Registration--01\16-10-20_LfngT2A3xCh-Dusp4T2A3xVen_E75_4_G2_Average_Subset_E1_ch1_t002.tif--transformed.mha
#
# Analysis
#

**Comment by HenningEMBL** [comment]
Ok, for now I just removed the crop option from the script, then it works

**Comment by tischi** [comment]
I also removed it, so you can download the latest version.
